/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufes.pss.trabalhofinal.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Usuário
 */
public class AplicarFiltroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarImagemView
     */
    public AplicarFiltroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboFiltros = new javax.swing.JComboBox<>();
        btnFechar = new javax.swing.JButton();
        btnRestaurarPadrao = new javax.swing.JButton();
        btnDesfazer = new javax.swing.JButton();
        pnlImagem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxAzul = new javax.swing.JCheckBox();
        cbxVerde = new javax.swing.JCheckBox();
        cbxVermelha = new javax.swing.JCheckBox();
        cbxEspelhada = new javax.swing.JCheckBox();
        cbxRotacao = new javax.swing.JCheckBox();
        cbxNegativo = new javax.swing.JCheckBox();
        cbxSepia = new javax.swing.JCheckBox();
        cbxPixelada = new javax.swing.JCheckBox();
        cbxTomDeCinza = new javax.swing.JCheckBox();
        cbxBrilho = new javax.swing.JCheckBox();

        jLabel1.setText("Conjunto de filtros pré-definidos");

        comboFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        btnFechar.setText("Fechar");

        btnRestaurarPadrao.setText("Restaurar Padrão");

        btnDesfazer.setText("Desfazer");

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(lblImagem);

        javax.swing.GroupLayout pnlImagemLayout = new javax.swing.GroupLayout(pnlImagem);
        pnlImagem.setLayout(pnlImagemLayout);
        pnlImagemLayout.setHorizontalGroup(
            pnlImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImagemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlImagemLayout.setVerticalGroup(
            pnlImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Filtros");

        cbxAzul.setText("Azul");

        cbxVerde.setText("Verde");

        cbxVermelha.setText("Vermelha");

        cbxEspelhada.setText("Espelhada");

        cbxRotacao.setText("Rotação da Imagem");

        cbxNegativo.setText("Negativo");

        cbxSepia.setText("Sépia");

        cbxPixelada.setText("Pixelada");

        cbxTomDeCinza.setText("Tom de Cinza");

        cbxBrilho.setText("Brilho");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbxAzul)
                    .addComponent(cbxVerde)
                    .addComponent(cbxVermelha)
                    .addComponent(cbxRotacao)
                    .addComponent(cbxNegativo)
                    .addComponent(cbxSepia)
                    .addComponent(cbxPixelada)
                    .addComponent(cbxTomDeCinza)
                    .addComponent(cbxBrilho)
                    .addComponent(cbxEspelhada))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAzul)
                .addGap(18, 18, 18)
                .addComponent(cbxVerde)
                .addGap(18, 18, 18)
                .addComponent(cbxVermelha)
                .addGap(18, 18, 18)
                .addComponent(cbxEspelhada)
                .addGap(18, 18, 18)
                .addComponent(cbxRotacao)
                .addGap(18, 18, 18)
                .addComponent(cbxNegativo)
                .addGap(18, 18, 18)
                .addComponent(cbxSepia)
                .addGap(18, 18, 18)
                .addComponent(cbxPixelada)
                .addGap(18, 18, 18)
                .addComponent(cbxTomDeCinza)
                .addGap(18, 18, 18)
                .addComponent(cbxBrilho)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDesfazer)
                                .addGap(18, 18, 18)
                                .addComponent(btnRestaurarPadrao)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnRestaurarPadrao)
                    .addComponent(btnDesfazer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnDesfazer() {
        return btnDesfazer;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnRestaurarPadrao() {
        return btnRestaurarPadrao;
    }

    public JLabel getLblImagem() {
        return lblImagem;
    }

    public JCheckBox getCbxAzul() {
        return cbxAzul;
    }

    public JCheckBox getCbxBrilho() {
        return cbxBrilho;
    }

    public JCheckBox getCbxEspelhada() {
        return cbxEspelhada;
    }

    public JCheckBox getCbxNegativo() {
        return cbxNegativo;
    }

    public JCheckBox getCbxPixelada() {
        return cbxPixelada;
    }

    public JCheckBox getCbxRotacao() {
        return cbxRotacao;
    }

    public JCheckBox getCbxSepia() {
        return cbxSepia;
    }

    public JCheckBox getCbxTomDeCinza() {
        return cbxTomDeCinza;
    }

    public JCheckBox getCbxVerde() {
        return cbxVerde;
    }

    public JCheckBox getCbxVermelha() {
        return cbxVermelha;
    }

    public JComboBox<String> getComboFiltros() {
        return comboFiltros;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRestaurarPadrao;
    private javax.swing.JCheckBox cbxAzul;
    private javax.swing.JCheckBox cbxBrilho;
    private javax.swing.JCheckBox cbxEspelhada;
    private javax.swing.JCheckBox cbxNegativo;
    private javax.swing.JCheckBox cbxPixelada;
    private javax.swing.JCheckBox cbxRotacao;
    private javax.swing.JCheckBox cbxSepia;
    private javax.swing.JCheckBox cbxTomDeCinza;
    private javax.swing.JCheckBox cbxVerde;
    private javax.swing.JCheckBox cbxVermelha;
    private javax.swing.JComboBox<String> comboFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JPanel pnlImagem;
    // End of variables declaration//GEN-END:variables
}
