/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufes.pss.trabalhofinal.view;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Valmir Aguiar
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMain = new javax.swing.JDesktopPane();
        txtNotificacoes = new javax.swing.JLabel();
        btnNotificacoes = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        btnSolicitacoesAcesso = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        itemAtualizacaoCadastro = new javax.swing.JMenuItem();
        itemEntrar = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();
        itemGerenciamentoUsuario = new javax.swing.JMenuItem();
        menuArquivos = new javax.swing.JMenu();
        itemVisualizarImagem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 800));

        javax.swing.GroupLayout desktopMainLayout = new javax.swing.GroupLayout(desktopMain);
        desktopMain.setLayout(desktopMainLayout);
        desktopMainLayout.setHorizontalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopMainLayout.setVerticalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        txtNotificacoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNotificacoes.setText("0 notificações");

        btnNotificacoes.setText("Visualizar notificações");

        txtUsuario.setText("Usuário: ");

        btnSolicitacoesAcesso.setText("Solicitações de acesso");

        menuUsuario.setText("Usuário");

        itemAtualizacaoCadastro.setText("Atualização de cadastro");
        menuUsuario.add(itemAtualizacaoCadastro);

        itemEntrar.setText("Entrar");
        menuUsuario.add(itemEntrar);

        itemSair.setText("Sair");
        menuUsuario.add(itemSair);

        itemGerenciamentoUsuario.setText("Gerenciamento de usuários");
        menuUsuario.add(itemGerenciamentoUsuario);

        barraMenu.add(menuUsuario);

        menuArquivos.setText("Arquivos");

        itemVisualizarImagem.setText("Visualizar Imagem");
        menuArquivos.add(itemVisualizarImagem);

        barraMenu.add(menuArquivos);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMain)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btnSolicitacoesAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopMain)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsuario)
                    .addComponent(btnSolicitacoesAcesso))
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JButton btnSolicitacoesAcesso;
    private javax.swing.JDesktopPane desktopMain;
    private javax.swing.JMenuItem itemAtualizacaoCadastro;
    private javax.swing.JMenuItem itemEntrar;
    private javax.swing.JMenuItem itemGerenciamentoUsuario;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemVisualizarImagem;
    private javax.swing.JMenu menuArquivos;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JLabel txtNotificacoes;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnNotificacoes() {
        return btnNotificacoes;
    }

    public JDesktopPane getDesktopMain() {
        return desktopMain;
    }

    public JMenuItem getItemVisualizarImagem() {
        return itemVisualizarImagem;
    }

    public JMenuItem getItemAtualizacaoCadastro() {
        return itemAtualizacaoCadastro;
    }

    public JMenuItem getItemEntrar() {
        return itemEntrar;
    }

    public JMenuItem getItemGerenciamentoUsuario() {
        return itemGerenciamentoUsuario;
    }

    public JMenuItem getItemSair() {
        return itemSair;
    }

    public JLabel getTxtNotificacoes() {
        return txtNotificacoes;
    }

    public JLabel getTxtUsuario() {
        return txtUsuario;
    }

    public JMenu getMenuArquivos() {
        return menuArquivos;
    }

    public JMenu getMenuUsuario() {
        return menuUsuario;
    }

    public JButton getBtnSolicitacoesAcesso() {
        return btnSolicitacoesAcesso;
    }
    
    
}
