/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufes.pss.trabalhofinal.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author Usuário
 */
public class VisualizarImagemView extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarImagemView
     */
    public VisualizarImagemView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagem = new javax.swing.JLabel();
        btnAplicarFiltro = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnCompartilhar = new javax.swing.JButton();

        btnFechar.setText("Fechar");

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(lblImagem);

        btnAplicarFiltro.setText("Aplicar Filtros");

        btnHistorico.setText("Historico");

        btnExcluir.setText("Excluir");

        btnExportar.setText("Exportar");

        btnCompartilhar.setText("Compartilhar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 254, Short.MAX_VALUE)
                        .addComponent(btnCompartilhar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnHistorico)
                        .addGap(18, 18, 18)
                        .addComponent(btnAplicarFiltro)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnAplicarFiltro)
                    .addComponent(btnHistorico)
                    .addComponent(btnExcluir)
                    .addComponent(btnExportar)
                    .addComponent(btnCompartilhar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAplicarFiltro() {
        return btnAplicarFiltro;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnHistorico() {
        return btnHistorico;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLblImagem() {
        return lblImagem;
    }

    public JButton getBtnCompartilhar() {
        return btnCompartilhar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JButton getBtnExportar() {
        return btnExportar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarFiltro;
    private javax.swing.JButton btnCompartilhar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables
}
