package view;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Endereco;
import model.Paciente;
import modelDAO.EnderecoDAO;
import modelDAO.PacienteDAO;

public class TelaPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPaciente
    */
    
    private Paciente paciente;
    private Endereco endereco;
    
    public TelaPaciente() {
        initComponents();
        
        btnSalvarPaciente.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnSalvarPacienteActionPerformed(evt);
        });

        btnVoltarPaciente.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnVoltarPacienteActionPerformed(evt);
        });

        btnPesquisar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnPesquisarActionPerformed(evt);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomePaciente = new javax.swing.JTextField();
        lblNomePaciente = new javax.swing.JLabel();
        lblCpfPaciente = new javax.swing.JLabel();
        txtCpfPaciente = new javax.swing.JTextField();
        lblTelefonePaciente = new javax.swing.JLabel();
        txtTelefonePaciente = new javax.swing.JTextField();
        lblSexoPaciente = new javax.swing.JLabel();
        lblDataNascimentoPaciente = new javax.swing.JLabel();
        txtDataNascimentoPaciente = new javax.swing.JTextField();
        lblEnderecoPaciente = new javax.swing.JLabel();
        lblLogradouroPaciente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtLogradouroPaciente = new javax.swing.JTextField();
        lblBairroPaciente = new javax.swing.JLabel();
        txtBairroPaciente = new javax.swing.JTextField();
        lblNumeroPaciente = new javax.swing.JLabel();
        txtNumeroPaciente = new javax.swing.JTextField();
        lblCepPaciente = new javax.swing.JLabel();
        txtCepPaciente = new javax.swing.JTextField();
        btnSalvarPaciente = new javax.swing.JButton();
        btnVoltarPaciente = new javax.swing.JButton();
        lblCartaoSus = new javax.swing.JLabel();
        txtCartaoSus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        lblEditarPaciente = new javax.swing.JLabel();
        txtSexoPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNomePaciente.setText("Nome do paciente:");

        lblCpfPaciente.setText("CPF:");

        lblTelefonePaciente.setText("Telefone de contato:");

        lblSexoPaciente.setText("Sexo:");

        lblDataNascimentoPaciente.setText("Data de nascimento:");

        lblEnderecoPaciente.setText("Endereço");

        lblLogradouroPaciente.setText("Logradouro: ");

        lblBairroPaciente.setText("Bairro:");

        lblNumeroPaciente.setText("Número");

        lblCepPaciente.setText("CEP:");

        btnSalvarPaciente.setText("Salvar");

        btnVoltarPaciente.setText("Voltar");

        lblCartaoSus.setText("Cartão SUS:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Paciente");

        lblPesquisa.setText("Cartão SUS:");

        btnPesquisar.setText("Pesquisar");

        lblEditarPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEditarPaciente.setText("Editar Paciente");

        txtSexoPaciente.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtLogradouroPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCepPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCepPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumeroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addComponent(lblNumeroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(btnSalvarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVoltarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNomePaciente)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblEnderecoPaciente)
                                                .addComponent(lblCartaoSus)
                                                .addComponent(lblLogradouroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(33, 33, 33)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDataNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDataNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblTelefonePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTelefonePaciente)
                                            .addComponent(lblSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(txtCartaoSus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarPaciente)
                    .addComponent(lblEditarPaciente))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePaciente)
                    .addComponent(lblTelefonePaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfPaciente)
                    .addComponent(lblDataNascimentoPaciente)
                    .addComponent(lblSexoPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblCartaoSus)
                .addGap(7, 7, 7)
                .addComponent(txtCartaoSus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEnderecoPaciente)
                .addGap(18, 18, 18)
                .addComponent(lblLogradouroPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogradouroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairroPaciente)
                    .addComponent(lblNumeroPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCepPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCepPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarPaciente;
    private javax.swing.JButton btnVoltarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBairroPaciente;
    private javax.swing.JLabel lblCartaoSus;
    private javax.swing.JLabel lblCepPaciente;
    private javax.swing.JLabel lblCpfPaciente;
    private javax.swing.JLabel lblDataNascimentoPaciente;
    private javax.swing.JLabel lblEditarPaciente;
    private javax.swing.JLabel lblEnderecoPaciente;
    private javax.swing.JLabel lblLogradouroPaciente;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblNumeroPaciente;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblSexoPaciente;
    private javax.swing.JLabel lblTelefonePaciente;
    private javax.swing.JTextField txtBairroPaciente;
    private javax.swing.JTextField txtCartaoSus;
    private javax.swing.JTextField txtCepPaciente;
    private javax.swing.JTextField txtCpfPaciente;
    private javax.swing.JTextField txtDataNascimentoPaciente;
    private javax.swing.JTextField txtLogradouroPaciente;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtNumeroPaciente;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtSexoPaciente;
    private javax.swing.JTextField txtTelefonePaciente;
    // End of variables declaration//GEN-END:variables


    public void btnSalvarPacienteActionPerformed (ActionEvent evt) {
        
        Paciente p = new Paciente();
        p.setIdPaciente(this.paciente.getIdPaciente());
        p.setNomePaciente(txtNomePaciente.getText());
        p.setCpf(txtCpfPaciente.getText());
        p.setTelefone(txtTelefonePaciente.getText());
        p.setDataNascimento(txtDataNascimentoPaciente.getText());
        p.setCartaoSus(txtCartaoSus.getText());
        p.setSexo(txtSexoPaciente.getText());
        
        Endereco end = new Endereco();
        end.setLogradouro(txtLogradouroPaciente.getText());
        end.setCep(txtCepPaciente.getText());
        end.setBairro(txtBairroPaciente.getText());
        end.setNumero(txtNumeroPaciente.getText());        
        end.setId_endereco(this.endereco.getId_endereco());
        try{
            if(txtNomePaciente.getText().equals("") || 
                    txtCpfPaciente.getText().equals("") || 
                    txtTelefonePaciente.getText().equals("") ||
                    txtDataNascimentoPaciente.getText().equals("") ||
                    txtCartaoSus.getText().equals("") || 
                    txtSexoPaciente.getText().equals("") ||
                    txtLogradouroPaciente.getText().equals("") ||
                    txtCepPaciente.getText().equals("") ||
                    txtBairroPaciente.getText().equals("") ||
                    txtNumeroPaciente.getText().equals("") 
            ) {
                JOptionPane.showMessageDialog(null, "Campos vazios não são permitidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }else{
                PacienteDAO pDAO = new PacienteDAO();
                EnderecoDAO eDAO = new EnderecoDAO();

                pDAO.updateOrIgnorePaciente(p);
                eDAO.updateOrIgnoreEndereco(end);

                JOptionPane.showMessageDialog(null, "Salvo com sucesso");
                limparCampos();
            }
            
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }           
    }
    
    private void btnPesquisarActionPerformed(ActionEvent evt) {
        try{
            PacienteDAO pDAO = new PacienteDAO();
            Paciente p = pDAO.getPaciente(txtPesquisa.getText());
            
            if(p != null) {
                EnderecoDAO eDAO = new EnderecoDAO();
                Endereco e = eDAO.getEndereco(p.getId_endereco());
                
                if(e != null) {
                    preencherCampos(p, e);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro no endereço! ");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Paciente inexistente! ");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnVoltarPacienteActionPerformed(ActionEvent evt) {
        dispose();
    }    
    
    private void preencherCampos(Paciente p, Endereco e) {
        //Paciente        
        txtCpfPaciente.setText(p.getCpf());
        txtDataNascimentoPaciente.setText(p.getDataNascimento());
        txtNomePaciente.setText(p.getNomePaciente());
        txtTelefonePaciente.setText(p.getTelefone());
        txtCartaoSus.setText(p.getCartaoSus());
        txtSexoPaciente.setText(p.getSexo());
        
        //Endereco
        txtBairroPaciente.setText(e.getBairro());
        txtCepPaciente.setText(e.getCep());
        txtLogradouroPaciente.setText(e.getLogradouro());
        txtNumeroPaciente.setText(e.getNumero());
       
        this.paciente = p;
        this.endereco = e;
    }
    
    private void limparCampos(){    
        txtBairroPaciente.setText("");
        txtCepPaciente.setText("");
        txtCpfPaciente.setText("");
        txtDataNascimentoPaciente.setText("");
        txtLogradouroPaciente.setText("");
        txtNomePaciente.setText("");
        txtNumeroPaciente.setText("");
        txtTelefonePaciente.setText("");
        txtCartaoSus.setText("");
    }        

}
