
package view;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import model.Endereco;
import model.Paciente;
import modelDAO.EnderecoDAO;
import modelDAO.PacienteDAO;

public class TelaCadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPaciente
     */
    public TelaCadastroPaciente() {
        initComponents();
        
       btnSalvarPaciente.addActionListener((java.awt.event.ActionEvent evt) -> {
           btnSalvarPacienteActionPerformed(evt);
       });
        
       btnVoltarPaciente.addActionListener((java.awt.event.ActionEvent evt) -> {
           btnVoltarPacienteActionPerformed(evt);
       });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomePaciente = new javax.swing.JTextField();
        lblNomePaciente = new javax.swing.JLabel();
        lblCpfPaciente = new javax.swing.JLabel();
        txtCpfPaciente = new javax.swing.JTextField();
        lblTelefonePaciente = new javax.swing.JLabel();
        txtTelefonePaciente = new javax.swing.JTextField();
        lblSexoPaciente = new javax.swing.JLabel();
        cboxSexoPaciente = new javax.swing.JComboBox<>();
        lblDataNascimentoPaciente = new javax.swing.JLabel();
        txtDataNascimentoPaciente = new javax.swing.JTextField();
        lblEnderecoPaciente = new javax.swing.JLabel();
        lblLogradouroPaciente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtLogradouroPaciente = new javax.swing.JTextField();
        lblBairroPaciente = new javax.swing.JLabel();
        txtBairroPaciente = new javax.swing.JTextField();
        lblNumeroPaciente = new javax.swing.JLabel();
        txtNumeroPaciente = new javax.swing.JTextField();
        lblCepPaciente = new javax.swing.JLabel();
        txtCepPaciente = new javax.swing.JTextField();
        btnSalvarPaciente = new javax.swing.JButton();
        btnVoltarPaciente = new javax.swing.JButton();
        lblCartaoSus = new javax.swing.JLabel();
        txtCartaoSus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNomePaciente.setText("Nome do paciente:");

        lblCpfPaciente.setText("CPF:");

        lblTelefonePaciente.setText("Telefone de contato:");

        lblSexoPaciente.setText("Sexo:");

        cboxSexoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        lblDataNascimentoPaciente.setText("Data de nascimento:");

        lblEnderecoPaciente.setText("Endereço");

        lblLogradouroPaciente.setText("Logradouro: ");

        lblBairroPaciente.setText("Bairro:");

        lblNumeroPaciente.setText("Número");

        lblCepPaciente.setText("CEP:");

        btnSalvarPaciente.setText("Salvar");

        btnVoltarPaciente.setText("Voltar");

        lblCartaoSus.setText("Cartão SUS:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Pacientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEnderecoPaciente)
                                    .addComponent(lblCartaoSus)
                                    .addComponent(lblLogradouroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtLogradouroPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNomePaciente))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblTelefonePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelefonePaciente)
                                        .addComponent(lblSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboxSexoPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCepPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCepPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumeroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addComponent(lblNumeroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(btnSalvarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVoltarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtCartaoSus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltarPaciente)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePaciente)
                    .addComponent(lblTelefonePaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfPaciente)
                    .addComponent(lblDataNascimentoPaciente)
                    .addComponent(lblSexoPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblCartaoSus)
                .addGap(7, 7, 7)
                .addComponent(txtCartaoSus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEnderecoPaciente)
                .addGap(18, 18, 18)
                .addComponent(lblLogradouroPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogradouroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairroPaciente)
                    .addComponent(lblNumeroPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCepPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCepPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarPaciente;
    private javax.swing.JButton btnVoltarPaciente;
    private javax.swing.JComboBox<String> cboxSexoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBairroPaciente;
    private javax.swing.JLabel lblCartaoSus;
    private javax.swing.JLabel lblCepPaciente;
    private javax.swing.JLabel lblCpfPaciente;
    private javax.swing.JLabel lblDataNascimentoPaciente;
    private javax.swing.JLabel lblEnderecoPaciente;
    private javax.swing.JLabel lblLogradouroPaciente;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblNumeroPaciente;
    private javax.swing.JLabel lblSexoPaciente;
    private javax.swing.JLabel lblTelefonePaciente;
    private javax.swing.JTextField txtBairroPaciente;
    private javax.swing.JTextField txtCartaoSus;
    private javax.swing.JTextField txtCepPaciente;
    private javax.swing.JTextField txtCpfPaciente;
    private javax.swing.JTextField txtDataNascimentoPaciente;
    private javax.swing.JTextField txtLogradouroPaciente;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtNumeroPaciente;
    private javax.swing.JTextField txtTelefonePaciente;
    // End of variables declaration//GEN-END:variables


    public void btnSalvarPacienteActionPerformed (java.awt.event.ActionEvent evt) {
        
        Paciente p = new Paciente();
        p.setNomePaciente(txtNomePaciente.getText());
        p.setCpf(txtCpfPaciente.getText());
        p.setTelefone(txtTelefonePaciente.getText());
        p.setDataNascimento(txtDataNascimentoPaciente.getText());
        p.setCartaoSus(txtCartaoSus.getText());
        p.setSexo(cboxSexoPaciente.getSelectedItem().toString());
        
        Endereco endereco = new Endereco();
        endereco.setLogradouro(txtLogradouroPaciente.getText());
        endereco.setCep(txtCepPaciente.getText());
        endereco.setBairro(txtBairroPaciente.getText());
        endereco.setNumero(txtNumeroPaciente.getText());
        
        try{
            EnderecoDAO endDAO = new EnderecoDAO();
            int id_endereco = endDAO.insertEndereco(endereco);
        
            if(id_endereco != -1){
                PacienteDAO pDAO = new PacienteDAO();
                
                Paciente pTemp = pDAO.getPaciente(p.getCartaoSus());
                
                if(pTemp == null){
                    pDAO.insertPaciente(p, id_endereco);
                    limparCampos();
                    JOptionPane.showMessageDialog(null, "Paciente cadastrado com sucesso!\nPaciente: "+p.getNomePaciente() );
                }else{
                    JOptionPane.showMessageDialog(null, "Erro - Cartão SUS já cadastrado" );
                }
            }else{
                JOptionPane.showMessageDialog(null, "Erro de id_endereco", "Erro", JOptionPane.ERROR_MESSAGE);
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }           
    }
    
    private void btnVoltarPacienteActionPerformed(ActionEvent evt) {
        dispose();
    }    
    
    private void limparCampos(){    
        txtBairroPaciente.setText("");
        txtCepPaciente.setText("");
        txtCpfPaciente.setText("");
        txtDataNascimentoPaciente.setText("");
        txtLogradouroPaciente.setText("");
        txtNomePaciente.setText("");
        txtNumeroPaciente.setText("");
        txtTelefonePaciente.setText("");
        txtCartaoSus.setText("");
    }        

}
