/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.ufes.pss.gestaofuncionarios.view;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Valmir Aguiar
 */
public class CalcularSalarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CalcularSalarioVIew
     */
    public CalcularSalarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnCalcular = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        txtDataCalculo = new javax.swing.JFormattedTextField();
        btnNaoCalculados = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtDataBusca = new javax.swing.JFormattedTextField();
        lblDataCalculo = new javax.swing.JLabel();

        setTitle("Calcular Salário");

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        btnCalcular.setText("Calcular");

        btnFechar.setText("Fechar");

        txtDataCalculo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        btnNaoCalculados.setText("Listar não calculados");

        btnBuscar.setText("Buscar por Data");

        txtDataBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        lblDataCalculo.setText("Data do Cálculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDataBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNaoCalculados))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDataCalculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNaoCalculados)
                    .addComponent(btnBuscar)
                    .addComponent(txtDataBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnFechar)
                    .addComponent(txtDataCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataCalculo))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnCalcular() {
        return btnCalcular;
    }

    public void setBtnCalcular(JButton btnCalcular) {
        this.btnCalcular = btnCalcular;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public void setBtnFechar(JButton btnFechar) {
        this.btnFechar = btnFechar;
    }

    public JButton getBtnNaoCalculados() {
        return btnNaoCalculados;
    }

    public void setBtnNaoCalculados(JButton btnNaoCalculados) {
        this.btnNaoCalculados = btnNaoCalculados;
    }

    public JTable getTblFuncionarios() {
        return tblFuncionarios;
    }

    public void setTblFuncionarios(JTable tblFuncionarios) {
        this.tblFuncionarios = tblFuncionarios;
    }

    public JFormattedTextField getTxtDataBusca() {
        return txtDataBusca;
    }

    public void setTxtDataBusca(JFormattedTextField txtDataBusca) {
        this.txtDataBusca = txtDataBusca;
    }

    public JFormattedTextField getTxtDataCalculo() {
        return txtDataCalculo;
    }

    public void setTxtDataCalculo(JFormattedTextField txtDataCalculo) {
        this.txtDataCalculo = txtDataCalculo;
    }

    public JLabel getLblDataCalculo() {
        return lblDataCalculo;
    }

    public void setLblDataCalculo(JLabel lblDataCalculo) {
        this.lblDataCalculo = lblDataCalculo;
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNaoCalculados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataCalculo;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JFormattedTextField txtDataBusca;
    private javax.swing.JFormattedTextField txtDataCalculo;
    // End of variables declaration//GEN-END:variables
}
